#!/usr/bin/env python3
"""Regenerate fonts.css from the woff2 files in fonts/.

The faces are embedded as data URIs rather than linked, so the type also
renders when a page is opened straight from disk — Chrome refuses font
requests over file:// as cross-origin. Runs offline; the unicode ranges
live in tools/fonts.manifest.json.

    python3 tools/build-fonts.py
"""
import base64, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
faces = json.loads((ROOT / "tools/fonts.manifest.json").read_text())

out = ['''/* ===========================================================
   Shippori Mincho (display) and Zen Kaku Gothic New (text),
   Latin subsets only, embedded as data URIs — no third-party
   requests, and the faces survive file:// as well as http.

   Generated by tools/build-fonts.py — do not edit by hand.
   =========================================================== */
''']

total = 0
for f in faces:
    path = ROOT / "fonts" / f["file"]
    if not path.exists():
        sys.exit(f"missing font file: {path}")
    data = base64.b64encode(path.read_bytes()).decode()
    total += path.stat().st_size
    out.append(f'''@font-face {{
  font-family: "{f["family"]}";
  font-style: normal;
  font-weight: {f["weight"]};
  font-display: swap;
  src: url(data:font/woff2;base64,{data}) format("woff2");
  unicode-range: {f["unicode_range"]};
}}
''')

(ROOT / "fonts.css").write_text("\n".join(out))
print(f"fonts.css: {len(faces)} faces, {total/1024:.0f} KB of woff2 embedded")
